// This file is auto-generated by @hey-api/openapi-ts

export type ActivityLogPublic = {
    id: string;
    entity_type: string;
    entity_id: string;
    action: string;
    user_id?: (string | null);
    detail?: (string | null);
    timestamp?: (string | null);
};

export type ActivityLogsPublic = {
    data: Array<ActivityLogPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BugCreate = {
    title: string;
    description?: (string | null);
    severity?: BugSeverity;
    status?: BugStatus;
    assignee_id?: (string | null);
    project_id: string;
};

export type BugPublic = {
    id: string;
    title: string;
    description?: (string | null);
    severity: BugSeverity;
    status: BugStatus;
    assignee_id?: (string | null);
    project_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type BugSeverity = 'low' | 'medium' | 'high' | 'critical';

export type BugsPublic = {
    data: Array<BugPublic>;
    count: number;
};

export type BugStatus = 'open' | 'in_progress' | 'fixed' | 'closed';

export type BugUpdate = {
    title?: (string | null);
    description?: (string | null);
    severity?: (BugSeverity | null);
    status?: (BugStatus | null);
    assignee_id?: (string | null);
};

export type DeploymentInfoPublic = {
    id: string;
    version: string;
    commit_sha?: (string | null);
    environment: string;
    status: DeploymentStatus;
    deployed_at?: (string | null);
};

export type DeploymentsPublic = {
    data: Array<DeploymentInfoPublic>;
    count: number;
};

export type DeploymentStatus = 'success' | 'failed' | 'in_progress';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IncidentCreate = {
    title: string;
    description?: (string | null);
    severity?: BugSeverity;
    assignee_id?: (string | null);
    project_id: string;
};

export type IncidentPublic = {
    id: string;
    title: string;
    description?: (string | null);
    severity: BugSeverity;
    status: IncidentStatus;
    assignee_id?: (string | null);
    project_id: string;
    opened_at?: (string | null);
    resolved_at?: (string | null);
};

export type IncidentsPublic = {
    data: Array<IncidentPublic>;
    count: number;
};

export type IncidentStatus = 'open' | 'investigating' | 'resolved';

export type IncidentUpdate = {
    title?: (string | null);
    description?: (string | null);
    severity?: (BugSeverity | null);
    status?: (IncidentStatus | null);
    assignee_id?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Priority = 'low' | 'medium' | 'high' | 'critical';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    description?: (string | null);
};

export type ProjectPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type TaskCreate = {
    title: string;
    description?: (string | null);
    status?: TaskStatus;
    priority?: Priority;
    assignee_id?: (string | null);
    project_id: string;
};

export type TaskPublic = {
    id: string;
    title: string;
    description?: (string | null);
    status: TaskStatus;
    priority: Priority;
    assignee_id?: (string | null);
    project_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatus = 'todo' | 'in_progress' | 'done' | 'cancelled';

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (TaskStatus | null);
    priority?: (Priority | null);
    assignee_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ActivityLogsReadActivityLogsData = {
    entityType?: (string | null);
    limit?: number;
    skip?: number;
};

export type ActivityLogsReadActivityLogsResponse = (ActivityLogsPublic);

export type BugsReadBugsData = {
    limit?: number;
    projectId?: (string | null);
    severity?: (BugSeverity | null);
    skip?: number;
    status?: (BugStatus | null);
};

export type BugsReadBugsResponse = (BugsPublic);

export type BugsCreateBugData = {
    requestBody: BugCreate;
};

export type BugsCreateBugResponse = (BugPublic);

export type BugsReadBugData = {
    id: string;
};

export type BugsReadBugResponse = (BugPublic);

export type BugsUpdateBugData = {
    id: string;
    requestBody: BugUpdate;
};

export type BugsUpdateBugResponse = (BugPublic);

export type BugsDeleteBugData = {
    id: string;
};

export type BugsDeleteBugResponse = (Message);

export type DevopsHealthzResponse = ({
    [key: string]: unknown;
});

export type DevopsReadyzResponse = ({
    [key: string]: unknown;
});

export type DevopsVersionResponse = ({
    [key: string]: unknown;
});

export type DevopsReadDeploymentsData = {
    limit?: number;
    skip?: number;
};

export type DevopsReadDeploymentsResponse = (DeploymentsPublic);

export type IncidentsReadIncidentsData = {
    limit?: number;
    projectId?: (string | null);
    skip?: number;
    status?: (IncidentStatus | null);
};

export type IncidentsReadIncidentsResponse = (IncidentsPublic);

export type IncidentsCreateIncidentData = {
    requestBody: IncidentCreate;
};

export type IncidentsCreateIncidentResponse = (IncidentPublic);

export type IncidentsReadIncidentData = {
    id: string;
};

export type IncidentsReadIncidentResponse = (IncidentPublic);

export type IncidentsUpdateIncidentData = {
    id: string;
    requestBody: IncidentUpdate;
};

export type IncidentsUpdateIncidentResponse = (IncidentPublic);

export type IncidentsDeleteIncidentData = {
    id: string;
};

export type IncidentsDeleteIncidentResponse = (Message);

export type IncidentsResolveIncidentData = {
    id: string;
};

export type IncidentsResolveIncidentResponse = (IncidentPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type TasksReadTasksData = {
    limit?: number;
    projectId?: (string | null);
    skip?: number;
    status?: (TaskStatus | null);
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    id: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    id: string;
    requestBody: TaskUpdate;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    id: string;
};

export type TasksDeleteTaskResponse = (Message);

export type TasksUpdateTaskStatusData = {
    id: string;
    status: TaskStatus;
};

export type TasksUpdateTaskStatusResponse = (TaskPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);